// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBceAiTYFU_vCI_dtvmIhV6bMMiqeg2EsI',
    appId: '1:643649065207:web:56d1af32c9d079b90403f2',
    messagingSenderId: '643649065207',
    projectId: 'bookmyload-d702d',
    authDomain: 'bookmyload-d702d.firebaseapp.com',
    storageBucket: 'bookmyload-d702d.firebasestorage.app',
    measurementId: 'G-DBQQ1HKWG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBugxbg8UwPICIqZpGAqXjA7CZum8r37rY',
    appId: '1:643649065207:android:49147014cac93bd10403f2',
    messagingSenderId: '643649065207',
    projectId: 'bookmyload-d702d',
    storageBucket: 'bookmyload-d702d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWgCGKqLEmYN2QIMNHpCj6CAHYJeEQPIA',
    appId: '1:643649065207:ios:23d8073cf962f3b30403f2',
    messagingSenderId: '643649065207',
    projectId: 'bookmyload-d702d',
    storageBucket: 'bookmyload-d702d.firebasestorage.app',
    iosBundleId: 'com.example.appleGrower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWgCGKqLEmYN2QIMNHpCj6CAHYJeEQPIA',
    appId: '1:643649065207:ios:23d8073cf962f3b30403f2',
    messagingSenderId: '643649065207',
    projectId: 'bookmyload-d702d',
    storageBucket: 'bookmyload-d702d.firebasestorage.app',
    iosBundleId: 'com.example.appleGrower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBceAiTYFU_vCI_dtvmIhV6bMMiqeg2EsI',
    appId: '1:643649065207:web:452ffbbb50eebe610403f2',
    messagingSenderId: '643649065207',
    projectId: 'bookmyload-d702d',
    authDomain: 'bookmyload-d702d.firebaseapp.com',
    storageBucket: 'bookmyload-d702d.firebasestorage.app',
    measurementId: 'G-1KY7PG8KC5',
  );
}
