import 'package:apple_grower/models/freightForwarder.dart';
import 'package:get/get_rx/src/rx_types/rx_types.dart';

import '../models/aadhati.dart';
import '../models/grower_model.dart';
import '../models/orchard_model.dart';
import '../models/consignment_model.dart';
import '../models/pack_house_model.dart';
import '../models/ladani_model.dart';
import '../models/driving_profile_model.dart';
import '../models/transport_model.dart';

final Rx<Grower> globalGrower = Grower(
  id: 'GROWER001',
  name: 'Rajesh Kumar',
  phoneNumber: '9876543210',
  address: 'Village Kotkhai, Tehsil Kotkhai, District Shimla, Himachal Pradesh',
  aadharNumber: '123456789012',
  pinCode: '171201',
  orchards: [
    Orchard(
      id: 'ORCH001',
      name: 'Main Orchard',
      location: 'Kotkhai Valley',
      numberOfFruitingTrees: 500,
      expectedHarvestDate: DateTime.now().add(Duration(days: 30)),
      boundaryPoints: [
        GPSPoint(latitude: 31.1234, longitude: 77.5678),
        GPSPoint(latitude: 31.1235, longitude: 77.5679),
        GPSPoint(latitude: 31.1236, longitude: 77.5680),
        GPSPoint(latitude: 31.1237, longitude: 77.5681),
      ],
      area: 5.2,
      boundaryImagePath: 'assets/orchards/main_orchard.png',
      cropStage: CropStage.walnutSize,
      estimatedBoxes: 2000,
      createdAt: DateTime.now().subtract(Duration(days: 30)),
      updatedAt: DateTime.now(),
    ),
    Orchard(
      id: 'ORCH002',
      name: 'North Field',
      location: 'Kullu Valley',
      numberOfFruitingTrees: 300,
      expectedHarvestDate: DateTime.now().add(Duration(days: 45)),
      boundaryPoints: [
        GPSPoint(latitude: 31.2234, longitude: 77.6678),
        GPSPoint(latitude: 31.2235, longitude: 77.6679),
        GPSPoint(latitude: 31.2236, longitude: 77.6680),
        GPSPoint(latitude: 31.2237, longitude: 77.6681),
      ],
      area: 3.8,
      boundaryImagePath: 'assets/orchards/north_field.png',
      cropStage: CropStage.fruitDevelopment,
      estimatedBoxes: 1200,
      createdAt: DateTime.now().subtract(Duration(days: 20)),
      updatedAt: DateTime.now(),
    ),
  ],
  commissionAgents: [
    Aadhati(
      id: 'Aadhati1',
      name: 'Aadhati1',
      contact: '9876543212',
      nameOfTradingFirm: 'Himachal Traders',
      tradingSinceYears: 15,
      firmType: 'Partnership',
      licenseNo: 'LIC123456',
      salesPurchaseLocationName: 'Kotkhai Market',
      locationOnGoogle: 'Kotkhai, Himachal Pradesh',
      appleBoxesPurchased2023: 5000,
      appleBoxesPurchased2024: 6000,
      estimatedTarget2025: 7000.0,
      needTradeFinance: true,
      noOfAppleGrowersServed: 25,
    ),
    Aadhati(
      id: 'Aadhati2',
      name: 'Aadhati2',
      contact: '9876543213',
      nameOfTradingFirm: 'Apple Valley Traders',
      tradingSinceYears: 10,
      firmType: 'Proprietorship',
      licenseNo: 'LIC789012',
      salesPurchaseLocationName: 'Shimla Market',
      locationOnGoogle: 'Shimla, Himachal Pradesh',
      appleBoxesPurchased2023: 3000,
      appleBoxesPurchased2024: 3500,
      estimatedTarget2025: 4000.0,
      needTradeFinance: false,
      noOfAppleGrowersServed: 15,
    ),
  ],
  corporateCompanies: [
    Ladani(
      id: 'LADANI001',
      name: 'LADANI001',
      contact: '9876543214',
      address: 'Industrial Area, Shimla, Himachal Pradesh',
      nameOfTradingFirm: 'Himachal Apple Corp',
      tradingSinceYears: 20,
      firmType: 'Private Limited',
      licenseNo: 'CORP123456',
      purchaseLocationAddress: 'Industrial Area, Shimla',
      licensesIssuingAPMC: 'Shimla APMC',
      locationOnGoogle: 'Shimla Industrial Area',
      appleBoxesPurchased2023: 10000,
      appleBoxesPurchased2024: 12000,
      estimatedTarget2025: 15000.0,
      perBoxExpensesAfterBidding: 150.0,
    ),
  ],
  packingHouses: [
    PackHouse(
      id: 'PACK001',
      name: 'Himalayan Packers',
      phoneNumber: '9876543211',
      address: 'Industrial Area, Shimla',
      gradingMachine: 'Automatic Grading System',
      sortingMachine: 'Color Sorting Machine',
      gradingMachineCapacity: '1000 boxes/hour',
      sortingMachineCapacity: '800 boxes/hour',
      machineManufacturer: 'AppleTech Industries',
      trayType: TrayType.bothSide,
      perDayCapacity: '5000 boxes',
      numberOfCrates: 2000,
      crateManufacture: 'Himalayan Crates',
      boxesPacked2023: 50000,
      boxesPacked2024: 60000,
      estimatedBoxes2025: 75000,
      geoLoaction: 'Shimla Industrial Area',
      numberOfGrowersServed: 50,
    ),
  ],
  consignments: [
    Consignment(
      id: 'CONS001',
      quality: 'Premium',
      category: 'A',
      numberOfBoxes: 100,
      numberOfPiecesInBox: 20,
      pickupOption: 'Own',
      shippingFrom: 'Kotkhai',
      shippingTo: 'Delhi',
      commissionAgent: Aadhati(
        id: 'Aadhati1',
        name: 'Himachal Traders Pvt Ltd',
        contact: '9876543212',
        nameOfTradingFirm: 'Himachal Traders',
        tradingSinceYears: 15,
        firmType: 'Partnership',
        licenseNo: 'LIC123456',
        salesPurchaseLocationName: 'Kotkhai Market',
        locationOnGoogle: 'Kotkhai, Himachal Pradesh',
        appleBoxesPurchased2023: 5000,
        appleBoxesPurchased2024: 6000,
        estimatedTarget2025: 7000.0,
        needTradeFinance: true,
        noOfAppleGrowersServed: 25,
      ),
      corporateCompany: Ladani(
        id: 'LADANI001',
        name: 'Himachal Apple Corporation',
        contact: '9876543214',
        address: 'Industrial Area, Shimla, Himachal Pradesh',
        nameOfTradingFirm: 'Himachal Apple Corp',
        tradingSinceYears: 20,
        firmType: 'Private Limited',
        licenseNo: 'CORP123456',
        purchaseLocationAddress: 'Industrial Area, Shimla',
        licensesIssuingAPMC: 'Shimla APMC',
        locationOnGoogle: 'Shimla Industrial Area',
        appleBoxesPurchased2023: 10000,
        appleBoxesPurchased2024: 12000,
        estimatedTarget2025: 15000.0,
        perBoxExpensesAfterBidding: 150.0,
      ),
      packingHouse: PackHouse(
        id: 'PACK001',
        name: 'Himalayan Packers',
        phoneNumber: '9876543211',
        address: 'Industrial Area, Shimla',
        gradingMachine: 'Automatic Grading System',
        sortingMachine: 'Color Sorting Machine',
        gradingMachineCapacity: '1000 boxes/hour',
        sortingMachineCapacity: '800 boxes/hour',
        machineManufacturer: 'AppleTech Industries',
        trayType: TrayType.bothSide,
        perDayCapacity: '5000 boxes',
        numberOfCrates: 2000,
        crateManufacture: 'Himalayan Crates',
        boxesPacked2023: 50000,
        boxesPacked2024: 60000,
        estimatedBoxes2025: 75000,
        geoLoaction: 'Shimla Industrial Area',
        numberOfGrowersServed: 50,
      ),
      hasOwnCrates: true,
      status: 'Keep',
      driver: DrivingProfile(
        drivingLicenseNo: 'DL123456',
        vehicleRegistrationNo: 'HP01AB1234',
        chassiNoOfVehicle: 'CH123456789',
        payloadCapacityApprovedByRto: '5 tons',
        grossVehicleWeight: '7 tons',
        noOfTyres: 6,
        permitOfVehicleDriving: 'All India',
        vehicleOwnerAdharGst: 'GST123456789',
        appleBoxesTransported2023: 2000,
        appleBoxesTransported2024: 2500,
        estimatedTarget2025: 3000.0,
        statesDrivenThrough: 'HP, HR, DL',
      ),
      createdAt: DateTime.now().subtract(Duration(days: 5)),
      updatedAt: DateTime.now(),
    ),
  ],
  createdAt: DateTime.now().subtract(Duration(days: 365)),
  updatedAt: DateTime.now(),
).obs;

final Rx<Aadhati> globalAadhati = Aadhati(
  id: 'AADHATI001',
  name: 'Himachal Traders',
  contact: '9876543212',
  apmc: 'Shimla APMC',
  address: 'Kotkhai Market, Shimla, Himachal Pradesh',
  nameOfTradingFirm: 'Himachal Traders',
  tradingSinceYears: 15,
  firmType: 'Partnership',
  licenseNo: 'LIC123456',
  salesPurchaseLocationName: 'Kotkhai Market',
  locationOnGoogle: 'Kotkhai, Himachal Pradesh',
  appleBoxesPurchased2023: 5000,
  appleBoxesPurchased2024: 6000,
  estimatedTarget2025: 7000.0,
  needTradeFinance: true,
  noOfAppleGrowersServed: 25,
  farmers: [],
  forwardBuyers: [],
  ladanis: [],
  truckServiceProviders: [],
).obs;

final Rx<PackHouse> packHouse = PackHouse(
  id: 'PH001',
  name: 'Green Valley Packing House',
  phoneNumber: '+91 9876543210',
  address: '123, Green Valley Road, Nashik, Maharashtra',
  gradingMachine: 'Yes',
  sortingMachine: 'Yes',
  gradingMachineCapacity: '1000 boxes per hour',
  sortingMachineCapacity: '800 boxes per hour',
  machineManufacturer: 'TechPack Industries',
  trayType: TrayType.bothSide,
  perDayCapacity: '8000 boxes',
  numberOfCrates: 500,
  crateManufacture: 'CrateCo',
  boxesPacked2023: 25000,
  boxesPacked2024: 30000,
  estimatedBoxes2025: 35000,
  geoLoaction: '19.9975° N, 73.7898° E',
  numberOfGrowersServed: 25,
  associatedGrowers: [],
  associatedCommissionAgents: [],
  associatedPackers: [],
  associatedPickers: [],
).obs;

final Rx<Ladani> globalLadani = Ladani(
  id: 'LADANI001',
  name: 'Himachal Apple Corporation',
  contact: '9876543214',
  address: 'Industrial Area, Shimla, Himachal Pradesh',
  nameOfTradingFirm: 'Himachal Apple Corp',
  tradingSinceYears: 20,
  firmType: 'Private Limited',
  licenseNo: 'CORP123456',
  purchaseLocationAddress: 'Industrial Area, Shimla',
  licensesIssuingAPMC: 'Shimla APMC',
  locationOnGoogle: 'Shimla Industrial Area',
  appleBoxesPurchased2023: 10000,
  appleBoxesPurchased2024: 12000,
  estimatedTarget2025: 15000.0,
  perBoxExpensesAfterBidding: 150.0,
  associatedAaddhatis: [
    Aadhati(
      id: 'Aadhati1',
      name: 'Himachal Traders Pvt Ltd',
      contact: '9876543212',
      nameOfTradingFirm: 'Himachal Traders',
      tradingSinceYears: 15,
      firmType: 'Partnership',
      licenseNo: 'LIC123456',
      salesPurchaseLocationName: 'Kotkhai Market',
      locationOnGoogle: 'Kotkhai, Himachal Pradesh',
      appleBoxesPurchased2023: 5000,
      appleBoxesPurchased2024: 6000,
      estimatedTarget2025: 7000.0,
      needTradeFinance: true,
      noOfAppleGrowersServed: 25,
    ),
  ],
  associatedBuyer: [
    FreightForwarder(
      id: 'BUYER001',
      name: 'Delhi Fruits Market',
      contact: '9876543215',
      address: 'Azadpur Mandi, Delhi',
      createdAt: DateTime.now().subtract(Duration(days: 30)),
      updatedAt: DateTime.now(),
    ),
  ],
  truckServiceProviders: [
    DrivingProfile(
      drivingLicenseNo: 'DL123456',
      vehicleRegistrationNo: 'HP01AB1234',
      chassiNoOfVehicle: 'CH123456789',
      payloadCapacityApprovedByRto: '5 tons',
      grossVehicleWeight: '7 tons',
      noOfTyres: 6,
      permitOfVehicleDriving: 'All India',
      vehicleOwnerAdharGst: 'GST123456789',
      appleBoxesTransported2023: 2000,
      appleBoxesTransported2024: 2500,
      estimatedTarget2025: 3000.0,
      statesDrivenThrough: 'HP, HR, DL',
    ),
  ],
).obs;

final Rx<FreightForwarder> globalFreightForwarder = FreightForwarder(
  id: 'FF001',
  name: 'Delhi Transport Services',
  contact: '9876543215',
  address: 'Azadpur Mandi, Delhi',
  licenseNo: 'FF123456',
  forwardingSinceYears: 10,
  licensesIssuingAuthority: 'Delhi Transport Authority',
  locationOnGoogle: 'Azadpur Mandi, Delhi',
  appleBoxesForwarded2023: 50000,
  appleBoxesForwarded2024: 60000,
  estimatedForwardingTarget2025: 75000,
  tradeLicenseOfAadhatiAttached: 'LIC789012',
  associatedAadhatis: [
    Aadhati(
      id: 'Aadhati1',
      name: 'Himachal Traders Pvt Ltd',
      contact: '9876543212',
      nameOfTradingFirm: 'Himachal Traders',
      tradingSinceYears: 15,
      firmType: 'Partnership',
      licenseNo: 'LIC123456',
      salesPurchaseLocationName: 'Kotkhai Market',
      locationOnGoogle: 'Kotkhai, Himachal Pradesh',
      appleBoxesPurchased2023: 5000,
      appleBoxesPurchased2024: 6000,
      estimatedTarget2025: 7000.0,
      needTradeFinance: true,
      noOfAppleGrowersServed: 25,
    ),
  ],
  associatedGrowers: [
    Grower(
      id: 'GROWER001',
      name: 'Rajesh Kumar',
      phoneNumber: '9876543210',
      address:
          'Village Kotkhai, Tehsil Kotkhai, District Shimla, Himachal Pradesh',
      aadharNumber: '123456789012',
      pinCode: '171201',
      orchards: [],
      commissionAgents: [],
      corporateCompanies: [],
      packingHouses: [],
      consignments: [],
      createdAt: DateTime.now().subtract(Duration(days: 365)),
      updatedAt: DateTime.now(),
    ),
  ],
  associatedPickupProviders: [
    DrivingProfile(
      id: 'DRIVER001',
      name: 'Ramesh Kumar',
      contact: '9876543216',
      drivingLicenseNo: 'DL123456',
      vehicleRegistrationNo: 'HP01AB1234',
      chassiNoOfVehicle: 'CH123456789',
      payloadCapacityApprovedByRto: '5 tons',
      grossVehicleWeight: '7 tons',
      noOfTyres: 6,
      permitOfVehicleDriving: 'All India',
      vehicleOwnerAdharGst: 'GST123456789',
      appleBoxesTransported2023: 2000,
      appleBoxesTransported2024: 2500,
      estimatedTarget2025: 3000.0,
      statesDrivenThrough: 'HP, HR, DL',
    ),
  ],
  associatedTruckServiceProviders: [
    DrivingProfile(
      id: 'DRIVER002',
      name: 'Suresh Kumar',
      contact: '9876543217',
      drivingLicenseNo: 'DL789012',
      vehicleRegistrationNo: 'HP02CD5678',
      chassiNoOfVehicle: 'CH987654321',
      payloadCapacityApprovedByRto: '8 tons',
      grossVehicleWeight: '12 tons',
      noOfTyres: 8,
      permitOfVehicleDriving: 'All India',
      vehicleOwnerAdharGst: 'GST987654321',
      appleBoxesTransported2023: 3000,
      appleBoxesTransported2024: 3500,
      estimatedTarget2025: 4000.0,
      statesDrivenThrough: 'HP, HR, DL, UP',
    ),
  ],
  createdAt: DateTime.now().subtract(Duration(days: 365)),
  updatedAt: DateTime.now(),
).obs;

final Rx<DrivingProfile> globalDriver = DrivingProfile(
  id: 'DRIVER001',
  name: 'Ramesh Kumar',
  contact: '9876543216',
  drivingLicenseNo: 'DL123456',
  vehicleRegistrationNo: 'HP01AB1234',
  chassiNoOfVehicle: 'CH123456789',
  payloadCapacityApprovedByRto: '5 tons',
  grossVehicleWeight: '7 tons',
  noOfTyres: 6,
  permitOfVehicleDriving: 'All India',
  vehicleOwnerAdharGst: 'GST123456789',
  appleBoxesTransported2023: 2000,
  appleBoxesTransported2024: 2500,
  estimatedTarget2025: 3000.0,
  statesDrivenThrough: 'HP, HR, DL',
  appleGrowers: [
    Grower(
      id: 'GROWER001',
      name: 'Rajesh Kumar',
      phoneNumber: '9876543210',
      address:
          'Village Kotkhai, Tehsil Kotkhai, District Shimla, Himachal Pradesh',
      aadharNumber: '123456789012',
      pinCode: '171201',
      orchards: [],
      commissionAgents: [],
      corporateCompanies: [],
      packingHouses: [],
      consignments: [],
      createdAt: DateTime.now().subtract(Duration(days: 365)),
      updatedAt: DateTime.now(),
    ),
  ],
  aadhatis: [
    Aadhati(
      id: 'Aadhati1',
      name: 'Himachal Traders Pvt Ltd',
      contact: '9876543212',
      nameOfTradingFirm: 'Himachal Traders',
      tradingSinceYears: 15,
      firmType: 'Partnership',
      licenseNo: 'LIC123456',
      salesPurchaseLocationName: 'Kotkhai Market',
      locationOnGoogle: 'Kotkhai, Himachal Pradesh',
      appleBoxesPurchased2023: 5000,
      appleBoxesPurchased2024: 6000,
      estimatedTarget2025: 7000.0,
      needTradeFinance: true,
      noOfAppleGrowersServed: 25,
    ),
  ],
  buyers: [
    FreightForwarder(
      id: 'FF001',
      name: 'Delhi Transport Services',
      contact: '9876543215',
      address: 'Azadpur Mandi, Delhi',
      licenseNo: 'FF123456',
      forwardingSinceYears: 10,
      licensesIssuingAuthority: 'Delhi Transport Authority',
      locationOnGoogle: 'Azadpur Mandi, Delhi',
      appleBoxesForwarded2023: 50000,
      appleBoxesForwarded2024: 60000,
      estimatedForwardingTarget2025: 75000,
      tradeLicenseOfAadhatiAttached: 'LIC789012',
      createdAt: DateTime.now().subtract(Duration(days: 365)),
      updatedAt: DateTime.now(),
    ),
  ],
).obs;

final Rx<Transport> globalTransport = Transport(
  name: 'Himachal Transport Union',
  contact: '9876543218',
  address: 'Transport Nagar, Shimla, Himachal Pradesh',
  nameOfTheTransportUnion: 'Himachal Transport Union',
  transportUnionRegistrationNo: 'TU123456',
  noOfVehiclesRegistered: 50,
  transportUnionPresidentAdharId: '123456789012',
  transportUnionSecretaryAdhar: '987654321012',
  noOfLightCommercialVehicles: 20,
  noOfMediumCommercialVehicles: 15,
  noOfHeavyCommercialVehicles: 15,
  appleBoxesTransported2023: 100000,
  appleBoxesTransported2024: 120000,
  estimatedTarget2025: 150000.0,
  statesDrivenThrough: 'HP, HR, DL, UP, UK',
  appleGrowers: [
    Grower(
      id: 'GROWER001',
      name: 'Rajesh Kumar',
      phoneNumber: '9876543210',
      address:
          'Village Kotkhai, Tehsil Kotkhai, District Shimla, Himachal Pradesh',
      aadharNumber: '123456789012',
      pinCode: '171201',
      orchards: [],
      commissionAgents: [],
      corporateCompanies: [],
      packingHouses: [],
      consignments: [],
      createdAt: DateTime.now().subtract(Duration(days: 365)),
      updatedAt: DateTime.now(),
    ),
  ],
  aadhatis: [
    Aadhati(
      id: 'Aadhati1',
      name: 'Himachal Traders Pvt Ltd',
      contact: '9876543212',
      nameOfTradingFirm: 'Himachal Traders',
      tradingSinceYears: 15,
      firmType: 'Partnership',
      licenseNo: 'LIC123456',
      salesPurchaseLocationName: 'Kotkhai Market',
      locationOnGoogle: 'Kotkhai, Himachal Pradesh',
      appleBoxesPurchased2023: 5000,
      appleBoxesPurchased2024: 6000,
      estimatedTarget2025: 7000.0,
      needTradeFinance: true,
      noOfAppleGrowersServed: 25,
    ),
  ],
  buyers: [
    FreightForwarder(
      id: 'FF001',
      name: 'Delhi Transport Services',
      contact: '9876543215',
      address: 'Azadpur Mandi, Delhi',
      licenseNo: 'FF123456',
      forwardingSinceYears: 10,
      licensesIssuingAuthority: 'Delhi Transport Authority',
      locationOnGoogle: 'Azadpur Mandi, Delhi',
      appleBoxesForwarded2023: 50000,
      appleBoxesForwarded2024: 60000,
      estimatedForwardingTarget2025: 75000,
      tradeLicenseOfAadhatiAttached: 'LIC789012',
      createdAt: DateTime.now().subtract(Duration(days: 365)),
      updatedAt: DateTime.now(),
    ),
  ],
  associatedDrivers: [
    DrivingProfile(
      id: 'DRIVER001',
      name: 'Ramesh Kumar',
      contact: '9876543216',
      drivingLicenseNo: 'DL123456',
      vehicleRegistrationNo: 'HP01AB1234',
      chassiNoOfVehicle: 'CH123456789',
      payloadCapacityApprovedByRto: '5 tons',
      grossVehicleWeight: '7 tons',
      noOfTyres: 6,
      permitOfVehicleDriving: 'All India',
      vehicleOwnerAdharGst: 'GST123456789',
      appleBoxesTransported2023: 2000,
      appleBoxesTransported2024: 2500,
      estimatedTarget2025: 3000.0,
      statesDrivenThrough: 'HP, HR, DL',
    ),
  ],
).obs;
